import java.util.Random;

public class Generator {
	static int n1=0;
	static int n2=0;
	static int n3=0;
	static int n4=0;
	static int n5=0;
	static int n6=0;
	static int n7=0;
	static int n8=0;
	static int n9=0;
	static int n10=0;
	static int n11=0;
	static int q=0;
	private static String[] domains;
	public static String generate_one_link(String first_part_link){
		StringBuilder generated_link = new StringBuilder();
		if(!first_part_link.equalsIgnoreCase("insert here first part of link, if you want")){
			generated_link.append("http://"+first_part_link);
		}else{
		generated_link.append("http://");//first_part_link must contain the last symbol "/"  (slash) and (v and numbers like server)
		}
		//generated_link.append(generateFirstPart()+"/");
		generated_link.append(generateSecondPart());
		generated_link.append(generateLastPart());
		String result = generated_link.toString();
		return result;
	}
	public static StringBuilder generateFirstPart(){
    //final String alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
    final String alphabet = "v";
		final String numbers = "0123456789";
		final int alpha = alphabet.length();
		final int numb = numbers.length();
		StringBuilder gneration = new StringBuilder();
		Random r = new Random();
			gneration.append(alphabet.charAt(r.nextInt(alpha)));
    		gneration.append(numbers.charAt(r.nextInt(numb)));
    		gneration.append(numbers.charAt(r.nextInt(numb)));
    		gneration.append(numbers.charAt(r.nextInt(numb)));
    		gneration.append(numbers.charAt(r.nextInt(numb)));
    		gneration.append(numbers.charAt(r.nextInt(numb)));
    		gneration.append(numbers.charAt(r.nextInt(numb)));
    		gneration.append(numbers.charAt(r.nextInt(numb)));
    		gneration.append(numbers.charAt(r.nextInt(numb)));
    		gneration.append(numbers.charAt(r.nextInt(numb)));
    	return gneration;
    	
    }

	public static StringBuilder generateSecondPart(){
		final String allSymbols = "abcdefghijklmnopqrstuvwxyz0123456789-_";
		int max=25;
		final int all = allSymbols.length();
		StringBuilder gneration = new StringBuilder();
		Random r = new Random();
		for(int k =1;k<=r.nextInt(max);k++){
			gneration.append(allSymbols.charAt(r.nextInt(all)));
		}
    	return gneration;
	}

	public static StringBuilder generateLastPart(){
		domains = new String[238];
		domains[0] =".ac";
		domains[1] =".ad";
		domains[2] =".ae";
		domains[3] =".af";
		domains[4] =".al";
		domains[5] =".am";
		domains[6] =".aq";
		domains[7] =".as";
		domains[8] =".asia";
		domains[9] =".at";
		domains[10] =".aw";
		domains[11] =".ax";
		domains[12] =".az";
		domains[13] =".ba";
		domains[14] =".bb";
		domains[15] =".be";
		domains[16] =".bg";
		domains[17] =".bh";
		domains[18] =".bi";
		domains[19] =".bj";
		domains[20] =".bm";
		domains[21] =".bo";
		domains[22] =".bs";
		domains[23] =".bt";
		domains[24] =".ca";
		domains[25] =".cat";
		domains[26] =".cd";
		domains[27] =".cf";
		domains[28] =".cg";
		domains[29] =".ch";
		domains[30] =".ci";
		domains[31] =".cl";
		domains[32] =".cm";
		domains[33] =".cn";
		domains[34] =".co";
		domains[35] =".co.ao";
		domains[36] =".co.bw";
		domains[37] =".co.ck";
		domains[38] =".co.fk";
		domains[39] =".co.id";
		domains[40] =".co.il";
		domains[41] =".co.in";
		domains[42] =".co.ke";
		domains[43] =".co.ls";
		domains[44] =".co.mz";
		domains[45] =".co.no";
		domains[46] =".co.nz";
		domains[47] =".co.th";
		domains[48] =".co.tz";
		domains[49] =".co.uk";
		domains[50] =".co.uz";
		domains[51] =".co.za";
		domains[52] =".co.zm";
		domains[53] =".co.zw";
		domains[54] =".com.ai";
		domains[55] =".com.ar";
		domains[56] =".com.au";
		domains[57] =".com.bd";
		domains[58] =".com.bn";
		domains[59] =".com.br";
		domains[60] =".com.cn";
		domains[61] =".com.cy";
		domains[62] =".com.eg";
		domains[63] =".com.et";
		domains[64] =".com.fj";
		domains[65] =".com.gh";
		domains[66] =".com.gn";
		domains[67] =".com.gt";
		domains[68] =".com.gu";
		domains[69] =".com.hk";
		domains[70] =".com.jm";
		domains[71] =".com.kh";
		domains[72] =".com.kw";
		domains[73] =".com.lb";
		domains[74] =".com.lr";
		domains[75] =".com.mt";
		domains[76] =".com.mv";
		domains[77] =".com.ng";
		domains[78] =".com.ni";
		domains[79] =".com.np";
		domains[80] =".com.nr";
		domains[81] =".com.om";
		domains[82] =".com.pa";
		domains[83] =".com.pl";
		domains[84] =".com.py";
		domains[85] =".com.qa";
		domains[86] =".com.sa";
		domains[87] =".com.sb";
		domains[88] =".com.sg";
		domains[89] =".com.sv";
		domains[90] =".com.sy";
		domains[91] =".com.tr";
		domains[92] =".com.tw";
		domains[93] =".com.ua";
		domains[94] =".com.uy";
		domains[95] =".com.ve";
		domains[96] =".com.vi";
		domains[97] =".com.vn";
		domains[98] =".com.ye";
		domains[99] =".coop";
		domains[100] =".cr";
		domains[101] =".cu";
		domains[102] =".cv";
		domains[103] =".cx";
		domains[104] =".cz";
		domains[105] =".de";
		domains[106] =".de.com";
		domains[107] =".dj";
		domains[108] =".dk";
		domains[109] =".dm";
		domains[110] =".do";
		domains[111] =".dz";
		domains[112] =".ec";
		domains[113] =".edu";
		domains[114] =".ee";
		domains[115] =".es";
		domains[116] =".eu";
		domains[117] =".eu.com";
		domains[118] =".fi";
		domains[119] =".fm";
		domains[120] =".fo";
		domains[121] =".fr";
		domains[122] =".ga";
		domains[123] =".gd";
		domains[124] =".ge";
		domains[125] =".gf";
		domains[126] =".gg";
		domains[127] =".gi";
		domains[128] =".gl";
		domains[129] =".gm";
		domains[130] =".gp";
		domains[131] =".gr";
		domains[132] =".gs";
		domains[133] =".gy";
		domains[134] =".hk";
		domains[135] =".hm";
		domains[136] =".hr";
		domains[137] =".ht";
		domains[138] =".hu";
		domains[139] =".ie";
		domains[140] =".im";
		domains[141] =".in";
		domains[142] =".in.ua";
		domains[143] =".io";
		domains[144] =".ir";
		domains[145] =".is";
		domains[146] =".it";
		domains[147] =".je";
		domains[148] =".jo";
		domains[149] =".jobs";
		domains[150] =".jp";
		domains[151] =".kg";
		domains[152] =".ki";
		domains[153] =".kiev.ua";
		domains[154] =".kn";
		domains[155] =".kr";
		domains[156] =".ky";
		domains[157] =".la";
		domains[158] =".li";
		domains[159] =".li";
		domains[160] =".lk";
		domains[161] =".lt";
		domains[162] =".lu";
		domains[163] =".lv";
		domains[164] =".ly";
		domains[165] =".ma";
		domains[166] =".mc";
		domains[167] =".md";
		domains[168] =".me.uk";
		domains[169] =".mg";
		domains[170] =".mk";
		domains[171] =".mo";
		domains[172] =".mp";
		domains[173] =".ms";
		domains[174] =".mu";
		domains[175] =".museum";
		domains[176] =".museum";
		domains[177] =".mx";
		domains[178] =".my";
		domains[179] =".na";
		domains[180] =".nc";
		domains[181] =".ne";
		domains[182] =".net.cn";
		domains[183] =".nf";
		domains[184] =".nl";
		domains[185] =".no";
		domains[186] =".nu";
		domains[187] =".org.cn";
		domains[188] =".org.uk";
		domains[189] =".pe";
		domains[190] =".ph";
		domains[191] =".pk";
		domains[192] =".pl";
		domains[193] =".pn";
		domains[194] =".pr";
		domains[195] =".ps";
		domains[196] =".pt";
		domains[197] =".re";
		domains[198] =".ro";
		domains[199] =".rs";
		domains[200] =".ru.com";
		domains[201] =".rw";
		domains[202] =".sd";
		domains[203] =".se";
		domains[204] =".sg";
		domains[205] =".sh";
		domains[206] =".si";
		domains[207] =".sk";
		domains[208] =".sl";
		domains[209] =".sm";
		domains[210] =".sn";
		domains[211] =".so";
		domains[212] =".sr";
		domains[213] =".st";
		domains[214] =".sz";
		domains[215] =".tc";
		domains[216] =".td";
		domains[217] =".tg";
		domains[218] =".tj";
		domains[219] =".tk";
		domains[220] =".tl";
		domains[221] =".tm";
		domains[222] =".tn";
		domains[223] =".to";
		domains[224] =".tt";
		domains[225] =".tw";
		domains[226] =".ua";
		domains[227] =".ug";
		domains[228] =".us";
		domains[229] =".uz";
		domains[230] =".vg";
		domains[231] =".vn";
		domains[232] =".vu";
		domains[233] =".ws";
		domains[234] =".moscow";
		domains[235] =".website";
		domains[236] =".center";
		domains[237] ="club";


		
		
		
		
		final int all = 238;
		StringBuilder gneration = new StringBuilder();
		Random r = new Random();
			gneration.append(domains[(r.nextInt(all))]);
    		
		return gneration;
	}
}
